# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e30caf6d2f6cbcbcee4b19f0c85a076435c14098b4f71e0b14510bee4e3609cf9167743c0501b7045583ff9ed9cac7a6d41fe70bf4ee9e51f4256386ec71bf1

test:
  secret_key_base: 132da2b03eaf09c14f0cdf3b6342ee2cdc38d21302c0587b092b5baaa9cf6a0c921f756c5e83fd447c0a88e4f09e0f3a433ab57e5acbf9c7f30bf66cc7fc872d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
