mongodb:
  ip: 127.0.0.1
  port: 27017
  user: admin
  password: admin
postgres:
  ip: 127.0.0.1
  port: 5432
  user: admin
  password: admin
mysql:
  ip: 127.0.0.1
  port: 3306
  user: root
  password: test

phpmyadmin: "https://phpmyadmin.ares-ensiie.eu"
